version: '3.8'
services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    depends_on:
      - redis
    # ajusta puertos/volúmenes según necesites
  redis:
    image: redis:6.2.18
    ports:
      - "6379:6379"









