version: "3.9"

services:
  mlflow:
    image: mlfloworg/mlflow:2.6.2
    command: server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./artifacts --host 0.0.0.0 --port 5000
    volumes:
      - ./mlflow:/mlflow
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl -f http://localhost:5000/health"]
      interval: 15s
      retries: 3

  prefect:
    image: prefecthq/prefect:2.7.5
    command: prefect orion start --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
    healthcheck:
      test: ["CMD", "curl -f http://localhost:4200/"]
      interval: 15s
      retries: 3

  grafana:
    image: grafana/grafana:9.5.2
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    healthcheck:
      test: ["CMD", "curl -f http://localhost:3000/api/health"]
      interval: 15s
      retries: 3

volumes:
  grafana-storage:

networks:
  default:
    external:
      name: robot2_network

