version: "3.9"
services:
  spark-master:
    image: bitnami/spark:3.3.2
    environment:
      - SPARK_MODE=master
  spark-worker:
    image: bitnami/spark:3.3.2
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077










